name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: slideflow-prod
  GCP_PROJECT_NUMBER: 925156909645
  GAR_LOCATION: us-central1
  SERVICE: nxd-core
  REGION: us-central1
  GCP_SERVICE_ACCOUNT: 925156909645-compute@developer.gserviceaccount.com
  WIF_POOL: nxd-github-pool
  WIF_PROVIDER: nxd-github-provider

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth via WIF
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          project_id: '${{ env.PROJECT_ID }}'
          workload_identity_provider: 'projects/${{ env.GCP_PROJECT_NUMBER }}/locations/global/workloadIdentityPools/${{ env.WIF_POOL }}/providers/${{ env.WIF_PROVIDER }}'
          service_account: '${{ env.GCP_SERVICE_ACCOUNT }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet

      - name: Build and Push Container
        run: |-
          gcloud builds submit --tag ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:latest .

      - name: Deploy to Cloud Run
        run: |-
          gcloud run deploy ${{ env.SERVICE }} \
            --image ${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.SERVICE }}/${{ env.SERVICE }}:latest \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --service-account ${{ env.GCP_SERVICE_ACCOUNT }} \
            --add-cloudsql-instances ${{ env.PROJECT_ID }}:${{ env.REGION }}:nxd-sql-instance
